update bash script

diff --git a/actions/port-forward/action.yaml b/actions/port-forward/action.yaml
--- a/actions/port-forward/action.yaml
+++ b/actions/port-forward/action.yaml
@@ -15,7 +15,7 @@ inputs:
     default: latest
     required: false
   timeout:
-    description: Timeout for portfowrd
+    description: Timeout in seconds for portfowrd
     default: "30"
     required: false
   kubeconfig:
@@ -31,17 +31,19 @@ runs:
         version: ${{ inputs.kubectl-version }}
 
     - name: Establish port forward
-      env:
-        TIMEOUT: "${{ inputs.timeout }}"
-      run: |
-        kubectl port-forward "services/${{ inputs.service }}" "${{ inputs.port }}:${{ inputs.port }}" --namespace ${{ inputs.namespace }} ${{ (inputs.kubeconfig != '' && format('--kubeconfig {0}', inputs.kubeconfig)) || '' }} &
-        # wait up to $TIMEOUT seconds for port forwarding
-        for _ in {1..$TIMEOUT}; do if grep -q "Forwarding from 127.0.0.1:${{ inputs.port }} -> ${{ inputs.port }}" port-forward.out; then
-          echo "Port forwarding done"
-          break
-        else
-          cat port-forward.out || true
-          echo "Portforwarding failed: Timeout reached"
-          exit 1
-        fi; done
       shell: bash
+      run: |
+        nohup kubectl port-forward "services/${{ inputs.service }}" "${{ inputs.port }}:${{ inputs.port }}" --namespace ${{ inputs.namespace }} ${{ (inputs.kubeconfig != '' && format('--kubeconfig {0}', inputs.kubeconfig)) || '' }} &
+        for ((i=1; i<=${{ inputs.timeout }}; i++));
+          do
+            if grep -q "Forwarding from 127.0.0.1:${{ inputs.port }} -> ${{ inputs.port }}" port-forward.out; then
+              echo "Port forwarding done"
+              exit 0
+            else
+              cat port-forward.out || true
+              echo "Waiting for port forwarding..."
+              sleep 1
+            fi;
+          done
+        echo "Timeout of ${{ inputs.timeout}} seconds reached. Port-forwarding failed."
+        exit 1
